module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#005049",
        "tertiary-fixed": "#71f8e4",
        "on-tertiary": "#ffffff",
        secondary: "#006a61",
        "on-tertiary-container": "#84ffec",
        "on-secondary-container": "#006f66",
        "surface-tint": "#006a63",
        "outline-variant": "#bdc9c6",
        "tertiary-container": "#00776b",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "inverse-primary": "#80d5cb",
        "on-primary-fixed-variant": "#00504a",
        surface: "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e2e7ff",
        "on-tertiary-fixed-variant": "#005048",
        "on-primary-container": "#a3faef",
        "surface-container-low": "#f2f3ff",
        "surface-variant": "#dae2fd",
        "surface-container": "#eaedff",
        "on-surface-variant": "#3e4947",
        tertiary: "#005c52",
        "primary-fixed-dim": "#80d5cb",
        "surface-dim": "#d2d9f4",
        outline: "#6e7977",
        "on-background": "#131b2e",
        "surface-bright": "#faf8ff",
        "inverse-surface": "#283044",
        primary: "#005c55",
        "secondary-fixed": "#89f5e7",
        "inverse-on-surface": "#eef0ff",
        "surface-container-highest": "#dae2fd",
        "tertiary-fixed-dim": "#4fdbc8",
        "on-surface": "#131b2e",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "secondary-container": "#86f2e4",
        background: "#faf8ff",
        "primary-fixed": "#9cf2e8",
        "error-container": "#ffdad6",
        "primary-container": "#0f766e",
        "on-secondary-fixed": "#00201d",
        "on-tertiary-fixed": "#00201c",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#6bd8cb",
        "on-primary-fixed": "#00201d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-sm": "1rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        gutter: "1.5rem",
        "space-md": "1rem",
        margin: "2rem",
        "gutter-sm": "1rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "title-md": ["Plus Jakarta Sans"],
        "label-md": ["Inter"],
        display: ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        caption: ["Inter"],
        "label-sm": ["Inter"],
        "body-sm": ["Inter"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        display: [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        caption: [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "500" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
      },
    },
  },
};
